<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SuccessTestFunction" Id="{a12dc10c-a75e-47c2-a1f7-c8979a1e8b02}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SuccessTestFunction : T_MAXSTRING
VAR_INPUT
	foo : T_MAXSTRING;
	hello : T_MAXSTRING;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SuccessTestFunction := concat(foo, hello);]]></ST>
    </Implementation>
    <LineIds Name="SuccessTestFunction">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>