<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="RejectWithMessageAsyncHandler" Id="{76f722c4-335d-4072-b575-36ba2411bf2a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RejectWithMessageAsyncHandler IMPLEMENTS I_AsynchronousRpcHandler
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Handle" Id="{6cced2f9-9720-439e-8ec3-902320a03d64}">
      <Declaration><![CDATA[METHOD Handle
VAR_INPUT
	Parameters : I_Deserializer;
	Response : I_AsynchronousRpcResponse;
END_VAR
VAR
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Response.RejectWithMessage('This is the reject message');]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>